# This file was generated by GoReleaser. DO NOT EDIT.
cask "thoop" do
  name "thoop"
  desc "WHOOP data in your terminal"
  homepage "https://github.com/garrettladley/thoop"
  version "0.0.12"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thoop"

  on_macos do
    on_intel do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_darwin_amd64.tar.gz"
      sha256 "a54fa7efbac725141da4ac195a3128bf4eaa793cdd1d4863c7736073813416f9"
    end
    on_arm do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_darwin_arm64.tar.gz"
      sha256 "8804f46f7f60b4d2d7da55e2faebe4e139b771c7a32309d6442f9b6126622b78"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_linux_amd64.tar.gz"
      sha256 "af33f4abc5fe25df994b5f329ea48cb5fcbe52197af0f15fd13f0b7c2fa3ff3b"
    end
    on_arm do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_linux_arm64.tar.gz"
      sha256 "9bf70abd88a86801860967be279e0c540fca8749ce31a703b22b57ff41c95d14"
    end
  end

  # No zap stanza required
end
