# This file was generated by GoReleaser. DO NOT EDIT.
cask "thoop" do
  name "thoop"
  desc "WHOOP data in your terminal"
  homepage "https://github.com/garrettladley/thoop"
  version "0.0.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thoop"

  on_macos do
    on_intel do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_darwin_amd64.tar.gz"
      sha256 "affc0aaf30ae942af18739451b8b346dcad91df435a88ca75a7da46f32037bfa"
    end
    on_arm do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_darwin_arm64.tar.gz"
      sha256 "90d2bd390cdc32a10885842e2ba857e589b0b19341c2a9626d1e56c10a6182ef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_linux_amd64.tar.gz"
      sha256 "a25632fa0ed0d7ed3526d56ac08e066621b1756ce975c77427db326e000c1ef8"
    end
    on_arm do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_linux_arm64.tar.gz"
      sha256 "6d6d7d25eea6ba6048e9f77d64ac0649c0e5c8188045dceb620b3543a28ed7e6"
    end
  end

  # No zap stanza required
end
