# This file was generated by GoReleaser. DO NOT EDIT.
cask "thoop" do
  name "thoop"
  desc "WHOOP data in your terminal"
  homepage "https://github.com/garrettladley/thoop"
  version "0.1.5"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "thoop"

  on_macos do
    on_intel do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_darwin_amd64.tar.gz"
      sha256 "9149e48a6d9bdb0418151dfb7942efc69e836f027d5d51f14bed97ab7b9b77ab"
    end
    on_arm do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_darwin_arm64.tar.gz"
      sha256 "e1975843030321d70070a2b326bc6bc594676b2dbe0dc7deaa1cd8db27c7d144"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_linux_amd64.tar.gz"
      sha256 "80400afac2507c7e04baca9530e83e72be538bf2c93313bd45116ba89e3c34dc"
    end
    on_arm do
      url "https://github.com/garrettladley/thoop/releases/download/v#{version}/thoop_#{version}_linux_arm64.tar.gz"
      sha256 "67dcbe4daeff7658d84202ee8ef559ba6a26a73aea545a78d9c9199c55497825"
    end
  end

  # No zap stanza required
end
